export const sampleData = [
    { id: 1, name: "Alice Johnson", role: "Engineer", department: "Development", age: 29 },
    { id: 2, name: "Bob Smith", role: "Manager", department: "Operations", age: 42 },
    { id: 3, name: "Charlie Davis", role: "Designer", department: "UI/UX", age: 31 },
    { id: 4, name: "Diana King", role: "Engineer", department: "Development", age: 27 },
    { id: 5, name: "Ethan Brown", role: "QA Analyst", department: "Testing", age: 34 },
    { id: 6, name: "Fiona Lee", role: "Scrum Master", department: "Agile", age: 37 },
    { id: 7, name: "George Wilson", role: "Engineer", department: "DevOps", age: 28 },
    { id: 8, name: "Hannah White", role: "HR Specialist", department: "Human Resources", age: 41 },
    { id: 9, name: "Ian Thomas", role: "Engineer", department: "Development", age: 26 },
    { id: 10, name: "Jane Miller", role: "Manager", department: "Sales", age: 39 },
    { id: 11, name: "Kevin Scott", role: "Engineer", department: "Development", age: 33 },
    { id: 12, name: "Laura Green", role: "Designer", department: "UI/UX", age: 30 },
    { id: 13, name: "Mark Young", role: "Engineer", department: "DevOps", age: 35 },
    { id: 14, name: "Nina Carter", role: "QA Analyst", department: "Testing", age: 29 },
    { id: 15, name: "Oscar Adams", role: "Engineer", department: "Development", age: 40 },
    { id: 16, name: "Paula Turner", role: "Manager", department: "Finance", age: 44 },
    { id: 17, name: "Quincy Hall", role: "Engineer", department: "Development", age: 25 },
    { id: 18, name: "Rachel Evans", role: "HR Specialist", department: "Human Resources", age: 38 },
    { id: 19, name: "Sam Wright", role: "Engineer", department: "DevOps", age: 32 },
    { id: 20, name: "Tina Lopez", role: "Designer", department: "UI/UX", age: 27 },
];
